# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3365cc937270e845a0a0705c48d03f01721a5e50ecf76c1afc8d2b6c9fe1cda85917d48d1b75dff7323f979322493705ca6a2c699aabd42b6eeb8cb9bed97113

test:
  secret_key_base: 301033e41d9a66e8557a6767b060fbbf398b9761976c2b5ccb58fdde7c3513d7c70660214382bcf0964aab8de98bc92c3678b8c3241c6ccd85a98ef5e8f18def

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
